services:
  App\Menu\Builder:
    arguments:
      - '@knp_menu.factory'
      - '@router.default'
      - '@translator'
      - '@doctrine.orm.default_entity_manager'
    tags:
      - { name: knp_menu.menu_builder, method: navMenu, alias: app_navmenu}
      - { name: knp_menu.menu_builder, method: lastRecipeMenu, alias: app_recipemenu}
      - { name: knp_menu.menu_builder, method: adminMenu, alias: app_adminmenu}