security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    encoders:
        App\UserBundle\Entity\User: sha512
    providers:
        main:
            id: fos_user.user_provider.username
    firewalls:
        admin:
            pattern: ^/
            anonymous: true
            provider: main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path: fos_user_security_logout
                target: fos_user_security_login
#        main:
#            pattern: ^/
#            anonymous: true
#            provider: main
#            form_login:
#                login_path: fos_user_security_login
#                check_path: fos_user_security_check
#            logout:
#                path: fos_user_security_logout
#                target: fos_user_security_login
#            remember_me:
#                secret: '%kernel.secret%'
#                lifetime: 86400
    role_hierarchy:
        ROLE_ADMIN: [ROLE_DEFAULT]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
#        - { path: ^/recipe/add, roles: ROLE_USER }
#        - { path: ^/recipe/delete, roles: ROLE_MODERATEUR }