app_ingredient_index:
  path: /
  controller: App\Controller\IngredientController::indexAction

app_ingredient_add:
  path: /add
  controller: App\Controller\IngredientController::addAction

app_ingredient_edit:
  path: /edit/{id}
  controller: App\Controller\IngredientController::editAction

app_ingredient_delete:
  path: /delete/{id}
  controller: App\Controller\IngredientController::deleteAction