app_recipe_index:
  path: /
  controller: App\Controller\RecipeController::indexAction

app_recipe_add:
  path: /add
  controller: App\Controller\RecipeController::addAction

app_recipe_edit:
  path: /edit/{slug}
  controller: App\Controller\RecipeController::editWithSlugAction

app_recipe_delete:
  path: /delete/{slug}
  controller: App\Controller\RecipeController::deleteWithSlugAction